#!/usr/bin/env python3
"""Phase 5 unseal step (AOV-249, pre-reg §4).

Joins blind_id -> (question_id, condition) using
tests/v0.2/cells/_blinding_seal.json and writes
*_unsealed.tsv siblings of the sealed rater TSVs.

Run from repo root:
    python tests/v0.2/scoring/_unseal.py

Idempotent. Pure stdlib. No protocol dependency.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SEAL = ROOT / "tests" / "v0.2" / "cells" / "_blinding_seal.json"
SCORING = ROOT / "tests" / "v0.2" / "scoring"

PAIRS = [
    ("EpistemicLogician_scores.tsv", "EpistemicLogician_scores_unsealed.tsv"),
    ("IndependentRater_scores.tsv", "IndependentRater_scores_unsealed.tsv"),
]

UNSEALED_HEADER = [
    "qid", "cond", "blind_id",
    "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8",
    "L2", "rater_note",
]


def load_mapping() -> dict[str, dict]:
    with SEAL.open("r", encoding="utf-8", newline="") as fh:
        seal = json.load(fh)
    return seal["mapping"]


def is_data_row(fields: list[str]) -> bool:
    if not fields:
        return False
    head = fields[0].strip()
    if not head or head.startswith("#"):
        return False
    if head == "blind_id":
        return False
    return len(head) == 16 and all(c in "0123456789abcdef" for c in head)


def unseal_one(src: Path, dst: Path, mapping: dict[str, dict]) -> int:
    rows_written = 0
    with src.open("r", encoding="utf-8", newline="") as fin, \
            dst.open("w", encoding="utf-8", newline="\n") as fout:
        fout.write("# Unsealed join of " + src.name +
                   " against tests/v0.2/cells/_blinding_seal.json\n")
        fout.write("# Generated by tests/v0.2/scoring/_unseal.py "
                   "(AOV-249, pre-reg §4 third-party unseal).\n")
        writer = csv.writer(fout, delimiter="\t", lineterminator="\n")
        writer.writerow(UNSEALED_HEADER)
        reader = csv.reader(fin, delimiter="\t")
        for fields in reader:
            if not is_data_row(fields):
                continue
            blind_id = fields[0].strip()
            entry = mapping.get(blind_id)
            if entry is None:
                raise SystemExit(
                    "blind_id " + blind_id + " in " + src.name +
                    " is not present in seal mapping")
            qid = entry["question_id"]
            cond = entry["condition"]
            scores = fields[1:10]
            l2 = fields[10] if len(fields) > 10 else ""
            note = fields[11] if len(fields) > 11 else ""
            while len(scores) < 9:
                scores.append("")
            writer.writerow([qid, cond, blind_id, *scores, l2, note])
            rows_written += 1
    return rows_written


def main() -> int:
    mapping = load_mapping()
    for src_name, dst_name in PAIRS:
        src = SCORING / src_name
        dst = SCORING / dst_name
        n = unseal_one(src, dst, mapping)
        print(f"{src_name}: {n} rows -> {dst_name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
